spring:
  application:
    name: greetingservice
#management:
#  endpoints:
#    web:
#      exposure:
#        include:
#        - '*'
greetingservice:
  greeting: "Ciao"
  default-value: "Mundo! (QA)"
